# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact Name')),
                ('organisation', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contact Organisation')),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('source_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Short name of source')),
                ('product_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Id for source')),
                ('contact_role', models.TextField(blank=True, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=256, null=True)),
                ('product_version', models.CharField(blank=True, max_length=256, null=True)),
                ('product_uri', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('product_references', models.TextField(blank=True, null=True, verbose_name='Paper citation')),
                ('product_citation', models.TextField(blank=True, null=True, verbose_name='Product citation')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('bbox_max_latitude', models.FloatField(verbose_name='Northern-most latitude')),
                ('bbox_min_latitude', models.FloatField(verbose_name='Southern-most latitude')),
                ('bbox_max_longitude', models.FloatField(verbose_name='Eastern-most longitude')),
                ('bbox_min_longitude', models.FloatField(verbose_name='Western-most longitude')),
                ('source_format_version', models.CharField(blank=True, max_length=256, null=True)),
                ('source_file', models.CharField(blank=True, max_length=256, null=True)),
                ('source_file_checksum', models.CharField(blank=True, max_length=256, null=True)),
                ('data_policy_document', models.URLField(blank=True, max_length=256, null=True, verbose_name='URL to Data Policy document')),
                ('total_station_count', models.IntegerField(verbose_name='Estimated station count')),
                ('data_centre_url', models.URLField(blank=True, max_length=256, null=True)),
                ('history', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True, verbose_name='Extra notes')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invapp.Contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Inventory',
            },
        ),
    ]
