# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('source_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('product_id', models.CharField(blank=True, max_length=256, null=True)),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('product_code', models.CharField(blank=True, max_length=256, null=True)),
                ('product_version', models.CharField(blank=True, max_length=256, null=True)),
                ('product_uri', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('product_references', models.TextField(blank=True, null=True)),
                ('product_citation', models.TextField(blank=True, null=True)),
                ('source_format_version', models.CharField(blank=True, max_length=256, null=True)),
                ('source_file', models.CharField(blank=True, max_length=256, null=True)),
                ('source_file_checksum', models.CharField(blank=True, max_length=256, null=True)),
                ('data_centre_url', models.URLField(blank=True, max_length=256, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('contact_role', models.TextField(blank=True, null=True)),
                ('history', models.CharField(blank=True, max_length=256, null=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
