# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-19 22:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CI_RoleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=32, verbose_name='Entry')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('source', models.CharField(max_length=8, verbose_name='Source of entry')),
                ('applicable_for', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='contact_role',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='total_station_count',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='adminArea',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='emailAddress',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='postalCode',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='privacy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telephone (incl. country and area code)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='contact_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invapp.Contact', verbose_name='Contact (for data)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='contact_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_data', to='invapp.Contact', verbose_name='Contact (for metadata)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='crs',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='data_centre',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='data_policy',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='geometry_type',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='mean_years_present',
            field=models.IntegerField(null=True, verbose_name='Mean number of years available (per station)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='optional_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_level',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Status of product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='record_status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Status of metadata record'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reporting_frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_format',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='spatial_domain',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='station_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated number of stations in dataset'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='update_frequency',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variables_attained',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='variables_not_attained',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='Contact Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.CharField(max_length=256, null=True, verbose_name='Contact Organisation'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Extra notes'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripton / abstract'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_citation',
            field=models.TextField(blank=True, null=True, verbose_name='Product citation (how to cite this data)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Product ID (set by provider)'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Dataset name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_references',
            field=models.TextField(blank=True, null=True, verbose_name='Papers / references describing the data'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source_id',
            field=models.CharField(default=uuid.uuid4, max_length=256, primary_key=True, serialize=False, verbose_name='Unique ID for source'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time / date this metadata entry was last edited'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='contact_role_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invapp.CI_RoleCode', verbose_name='Role (for data)'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='contact_role_metadata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_role_data', to='invapp.CI_RoleCode', verbose_name='Role (for metadata contact)'),
        ),
    ]
