# Generated by Django 2.0.7 on 2018-07-31 12:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descripton / abstract'),
        ),
    ]
