# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0002_auto_20180711_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bbox_max_latitude',
            field=models.FloatField(default=50.1, verbose_name='Northern-most latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='bbox_max_longitude',
            field=models.FloatField(default=20.1, verbose_name='Eastern-most longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='bbox_min_latitude',
            field=models.FloatField(default=-20.3, verbose_name='Southern-most latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='bbox_min_longitude',
            field=models.FloatField(default=-40.5, verbose_name='Western-most longitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='data_policy_document',
            field=models.URLField(blank=True, max_length=256, null=True, verbose_name='URL to Data Policy document'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 0, 0), verbose_name='End date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='organisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_station_count',
            field=models.IntegerField(default=2475, verbose_name='Estimated station count'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Extra notes'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_citation',
            field=models.TextField(blank=True, null=True, verbose_name='Product citation'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Id for source'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_references',
            field=models.TextField(blank=True, null=True, verbose_name='Paper citation'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Short name of source'),
        ),
    ]
