# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0003_auto_20180711_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Contact details'),
        ),
    ]
